import GraphicsAugmentedRealityCanonicalLaneLean.AdmissibleClass
import GraphicsAugmentedRealityCanonicalLaneLean.Projection
import GraphicsAugmentedRealityCanonicalLaneLean.BridgeLemmas
import GraphicsAugmentedRealityCanonicalLaneLean.GateLemmas
import GraphicsAugmentedRealityCanonicalLaneLean.CameraProjectionModel
import GraphicsAugmentedRealityCanonicalLaneLean.SpatialMappingPipeline
import GraphicsAugmentedRealityCanonicalLaneLean.VirtualObjectRegistration
import GraphicsAugmentedRealityCanonicalLaneLean.FinalTheorem

namespace HautevilleHouse
namespace GraphicsAugmentedRealityCanonicalLaneLean

-- Root module combining all submodules

end GraphicsAugmentedRealityCanonicalLaneLean
end HautevilleHouse